In [5]:
import pandas as pd

df_raw = pd.read_csv("../data/raw/nifty50.csv")
df_raw.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI
1,Date,NaN,NaN,NaN,NaN,NaN
2,2007-09-17,4494.64990234375,4549.0498046875,4482.85009765625,4518.4501953125,0
3,2007-09-18,4546.2001953125,4551.7998046875,4481.5498046875,4494.10009765625,0
4,2007-09-19,4732.35009765625,4739.0,4550.25,4550.25,0

In [7]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/nifty50.csv",
    skiprows=3,      # Skip all junk rows
    header=None
)

df.columns = ["Date", "Close", "High", "Low", "Open", "Volume"]

# Convert Date safely
df["Date"] = pd.to_datetime(df["Date"], format="%Y-%m-%d", errors="coerce")

# Drop rows where date failed
df = df.dropna(subset=["Date"])

# Set index
df.set_index("Date", inplace=True)

df = df.sort_index()

df.head()

                  Close         High          Low         Open  Volume
Date
2007-09-17  4494.649902  4549.049805  4482.850098  4518.450195       0
2007-09-18  4546.200195  4551.799805  4481.549805  4494.100098       0
2007-09-19  4732.350098  4739.000000  4550.250000  4550.250000       0
2007-09-20  4747.549805  4760.850098  4721.149902  4734.850098       0
2007-09-21  4837.549805  4855.700195  4733.700195  4752.950195       0